# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.23.2/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jetson/siamfc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jetson/siamfc/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.23.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jetson/siamfc/test/CMakeFiles /home/jetson/siamfc/test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jetson/siamfc/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named siamfc_det

# Build rule for target.
siamfc_det: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 siamfc_det
.PHONY : siamfc_det

# fast build rule for target.
siamfc_det/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/build
.PHONY : siamfc_det/fast

siamfc_det1.o: siamfc_det1.cpp.o
.PHONY : siamfc_det1.o

# target to build an object file
siamfc_det1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/siamfc_det1.cpp.o
.PHONY : siamfc_det1.cpp.o

siamfc_det1.i: siamfc_det1.cpp.i
.PHONY : siamfc_det1.i

# target to preprocess a source file
siamfc_det1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/siamfc_det1.cpp.i
.PHONY : siamfc_det1.cpp.i

siamfc_det1.s: siamfc_det1.cpp.s
.PHONY : siamfc_det1.s

# target to generate assembly for a file
siamfc_det1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/siamfc_det1.cpp.s
.PHONY : siamfc_det1.cpp.s

src/postprocess.o: src/postprocess.cu.o
.PHONY : src/postprocess.o

# target to build an object file
src/postprocess.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/src/postprocess.cu.o
.PHONY : src/postprocess.cu.o

src/postprocess.i: src/postprocess.cu.i
.PHONY : src/postprocess.i

# target to preprocess a source file
src/postprocess.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/src/postprocess.cu.i
.PHONY : src/postprocess.cu.i

src/postprocess.s: src/postprocess.cu.s
.PHONY : src/postprocess.s

# target to generate assembly for a file
src/postprocess.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/src/postprocess.cu.s
.PHONY : src/postprocess.cu.s

src/preprocess.o: src/preprocess.cu.o
.PHONY : src/preprocess.o

# target to build an object file
src/preprocess.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/src/preprocess.cu.o
.PHONY : src/preprocess.cu.o

src/preprocess.i: src/preprocess.cu.i
.PHONY : src/preprocess.i

# target to preprocess a source file
src/preprocess.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/src/preprocess.cu.i
.PHONY : src/preprocess.cu.i

src/preprocess.s: src/preprocess.cu.s
.PHONY : src/preprocess.s

# target to generate assembly for a file
src/preprocess.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siamfc_det.dir/build.make CMakeFiles/siamfc_det.dir/src/preprocess.cu.s
.PHONY : src/preprocess.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... siamfc_det"
	@echo "... siamfc_det1.o"
	@echo "... siamfc_det1.i"
	@echo "... siamfc_det1.s"
	@echo "... src/postprocess.o"
	@echo "... src/postprocess.i"
	@echo "... src/postprocess.s"
	@echo "... src/preprocess.o"
	@echo "... src/preprocess.i"
	@echo "... src/preprocess.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

